name: Fourth question
run-name: ${{ github.actor }} compiling based on CMakeLists.txt
on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Adding gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest -b release-1.11.0

  - name: Config worker with tests
    run: cmake -H. -B ${{github.workspace}}/build -DBUILD_TESTS=ON

  - name: Build worker
    run: cmake --build ${{github.workspace}}/build

  - name: Run tests
    run: build/check

  - name: Build for worker.cpp
    run: |
      cmake -H. -B_build -DBUILD_WORKER=ON
      cmake --build _build
 
  - name: Test if worker.cpp actually present
    run: ./_build/work

  - name: Make artifact from compiled main
    uses: actions/upload-artifact@v4
    with:
      name: compiled_worker_cpp
      path: _build/work
